[build]
  command = "yarn build"
  publish = "./site/public"

[template.environment]
  GITHUB_REPO_URL = "Github repository URL"
  GITHUB_ACCESS_TOKEN = "Github access token (optional for public repos)"
