[build]
  command = "yarn build"
  publish = "public"

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"

[template.environment]
  GITHUB_REPO_URL = "Github repository URL"
  GITHUB_ACCESS_TOKEN = "Github access token (optional for public repos)"