[build]
  command = "yarn build"
  publish = "site/public"

  [build.environment]
    YARN_VERSION = "1.13.0"

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"

[template]
  incoming-hooks = ["Github Releases"]

  [template.environment]
    REPO_URL = "Github repository URL"
    GITHUB_TOKEN = "Github access token (optional for public repos)"
