[build]
  command = "npm run build"
  publish = "public"

[template.environment]
  GITHUB_REPO_OWNER = "Github repository owner"
  GITHUB_REPO_NAME = "Github repository name"
  GITHUB_ACCESS_TOKEN = "Github access token"
  STYLESHEET_URL = "Stylesheet URL (optional)"