[build]
  command = "cd ./widget && yarn && yarn build && cd ../ && yarn build"
  publish = "public"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "ALLOW" 
    Access-Control-Allow-Origin = "'*'"

[template.environment]
  GITHUB_REPO_URL = "Github repository URL"
  GITHUB_ACCESS_TOKEN = "Github access token (optional for public repos)"