[build]
  command = "cd ./widget && yarn && yarn build && cd ../ && yarn build"
  publish = "public"

[template.environment]
  GITHUB_REPO_URL = "Github repository URL"
  GITHUB_ACCESS_TOKEN = "Github access token (optional for public repos)"
