[build]
  publish = "site/public"

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"

[template]
  incoming-hooks = ["Github Releases"]

[template.environment]
  GITHUB_REPO_URL = "Github repository URL"
  GITHUB_ACCESS_TOKEN = "Github access token (optional for public repos)"
  TITLE = "Site title (optional, defaults to repo title)"
  LOGO_URL = "URL of your logo (optional, defaults to repo owner avatar)"
  PRIMARY_COLOR = "Primary theme color (optional, defaults to repo owner avatar color)"
