version: 2
jobs:
  build_first_example:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      - run:
            name: Build first example
            command: FIRST_EXAMPLE_URL=$(
                now
                  --token=$NOW_TOKEN
                  --build-env GITHUB_REPO_URL=https://github.com/reduxjs/redux
                  --public
              )

  build_second_example:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      - run:
            name: Build second example
            command: SECOND_EXAMPLE_URL=$(
                now
                  --token=$NOW_TOKEN
                  --build-env GITHUB_REPO_URL=https://github.com/vuejs/vue
                  --public
              )

  build_third_example:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      - run:
            name: Build third example
            command: THIRD_EXAMPLE_URL=$(
                now
                  --token=$NOW_TOKEN
                  --build-env GITHUB_REPO_URL=https://github.com/atlassian/react-beautiful-dnd
                  --public
              )

  build_docs:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      - run:
            name: Build docs
            command: now
              --local-config=docs/now.json
              --token=$NOW_TOKEN
              --build-env FIRST_EXAMPLE_URL=$FIRST_EXAMPLE_URL
              --build-env SECOND_EXAMPLE_URL=$SECOND_EXAMPLE_URL
              --build-env THIRD_EXAMPLE_URL=$THIRD_EXAMPLE_URL
              --public
        

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build_first_example:
          context: org-global

      - build_second_example:
          context: org-global

      - build_third_example:
          context: org-global

      - build_docs:
          requires:
            - build_first_example
            - build_second_example
            - build_third_example
          context: org-global
