version: 2
jobs:
  build_first_example:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - restore_cache:
          name: Restore Site Yarn Package Cache
          keys:
            - yarn-packages-site-{{ checksum "yarn.lock" }}

      - run:
          name: Install Site Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Site Yarn Package Cache
          key: yarn-packages-site-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build First Example
          command: GITHUB_REPO_URL=https://github.com/reduxjs/redux URL=https://changelog-first.now.sh yarn build

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Deploy First Example
          command: FIRST_EXAMPLE_URL=$(
            now
            --token=$NOW_TOKEN
            --public
            )

            now alias $FIRST_EXAMPLE_URL changelog-first
            --token=$NOW_TOKEN

  build_second_example:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - restore_cache:
          name: Restore Site Yarn Package Cache
          keys:
            - yarn-packages-site-{{ checksum "yarn.lock" }}

      - run:
          name: Install Site Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Site Yarn Package Cache
          key: yarn-packages-site-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build Second Example
          command: GITHUB_REPO_URL=https://github.com/vuejs/vue URL=https://changelog-second.now.sh yarn build

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Deploy Second Example
          command: SECOND_EXAMPLE_URL=$(
            now
            --token=$NOW_TOKEN
            --public
            )

            now alias $SECOND_EXAMPLE_URL changelog-first
            --token=$NOW_TOKEN

  build_third_example:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - restore_cache:
          name: Restore Site Yarn Package Cache
          keys:
            - yarn-packages-site-{{ checksum "yarn.lock" }}

      - run:
          name: Install Site Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Site Yarn Package Cache
          key: yarn-packages-site-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build Third Example
          command: GITHUB_REPO_URL=https://github.com/atlassian/react-beautiful-dnd URL=https://changelog-third.now.sh yarn build

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Deploy Third Example
          command: THIRD_EXAMPLE_URL=$(
            now
            --token=$NOW_TOKEN
            --public
            )

            now alias $THIRD_EXAMPLE_URL changelog-first
            --token=$NOW_TOKEN

  build_docs:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - navigate_to_docs:
          name: Navigate To Docs Folder
          command: cd docs

      - restore_cache:
          name: Restore Docs Yarn Package Cache
          keys:
            - yarn-packages-docs-{{ checksum "yarn.lock" }}

      - run:
          name: Install Docs Dependencies
          command: cd docs && yarn install --frozen-lockfile

      - save_cache:
          name: Save Docs Yarn Package Cache
          key: yarn-packages-docs-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build Docs
          command: FIRST_EXAMPLE_URL=https://changelog-first.now.sh SECOND_EXAMPLE_URL=https://changelog-second.now.sh THIRD_EXAMPLE_URL=https://changelog-third.now.sh yarn build

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Deploy Docs
          command: now --token=$NOW_TOKEN --public

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build_first_example
      - build_second_example
      - build_third_example

      - build_docs:
          requires:
            - build_first_example
            - build_second_example
            - build_third_example
