version: 2
jobs:
  build_first_example:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Build first example
          command: FIRST_EXAMPLE_URL=$(
            now
            --token=$NOW_TOKEN
            --build-env GITHUB_REPO_URL=https://github.com/reduxjs/redux
            --build-env URL=https://changelog-first.now.sh
            --public
            )

            now alias $FIRST_EXAMPLE_URL changelog-first
            --token=$NOW_TOKEN

  build_second_example:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Build second example
          command: SECOND_EXAMPLE_URL=$(
            now
            --token=$NOW_TOKEN
            --build-env GITHUB_REPO_URL=https://github.com/vuejs/vue
            --build-env URL=https://changelog-second.now.sh
            --public
            )

            now alias $SECOND_EXAMPLE_URL changelog-second
            --token=$NOW_TOKEN

  build_third_example:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Build third example
          command: THIRD_EXAMPLE_URL=$(
            now
            --token=$NOW_TOKEN
            --build-env GITHUB_REPO_URL=https://github.com/atlassian/react-beautiful-dnd
            --build-env URL=https://changelog-third.now.sh
            --public
            )

            now alias $THIRD_EXAMPLE_URL changelog-third
            --token=$NOW_TOKEN

  build_docs:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Build docs
          command: cd docs

            DOCS_URL=$(
            now
            --token=$NOW_TOKEN
            --build-env FIRST_EXAMPLE_URL=https://changelog-first.now.sh
            --build-env SECOND_EXAMPLE_URL=https://changelog-second.now.sh
            --build-env THIRD_EXAMPLE_URL=https://changelog-third.now.sh
            --public
            )

            now alias $DOCS_URL changelog-docs --token=$NOW_TOKEN

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build_first_example
      - build_second_example
      - build_third_example

      - build_docs:
          requires:
            - build_first_example
            - build_second_example
            - build_third_example
